const vehicles = [
  {
    _id: 99,
    model: 'A6',
    make: 'Audi',
    regDate: '2006',
    power: 110,
    capacity: 2000,
    mileage: 50000,
    bodyType: 'sedan',
    price: 10000,
    priceDiscount: 5,
    fuel: 'diesel',
    transmission: 'manual',
    city: 'Tallinn',
    countryCode: 'EE',
    country: 'Estonia',
    urgent: true,
    featured: true,
    recommended: false,
    images: [
      {
        order: 0,
        url:
          'https://img.longo.group/drz5zvoaf/image/upload/c_fill,f_jpg,h_813,w_1084/hpkyty62jlu5hm94cdu4.jpg',
      },
    ],
  },
  {
    _id: 2,
    model: 'A6',
    make: 'Audi',
    regDate: '2006',
    power: 110,
    capacity: 2000,
    mileage: 50000,
    bodyType: 'sedan',
    price: 10000,
    priceDiscount: 5,
    fuel: 'diesel',
    transmission: 'manual',
    city: 'Tallinn',
    countryCode: 'EE',
    country: 'Estonia',
    urgent: true,
    featured: true,
    recommended: false,
    images: [
      {
        order: 0,
        url:
          'https://img.longo.group/drz5zvoaf/image/upload/c_fill,f_jpg,h_813,w_1084/hpkyty62jlu5hm94cdu4.jpg',
      },
    ],
  },
  {
    _id: 1,
    model: 'i5',
    make: 'BMW',
    regDate: '2020',
    power: 220,
    capacity: null,
    mileage: 2000,
    bodyType: 'sedan',
    price: 50000,
    priceDiscount: 12,
    fuel: 'electric',
    transmission: 'automatic',
    city: 'Tallinn',
    countryCode: 'EE',
    country: 'Estonia',
    urgent: false,
    featured: true,
    recommended: true,
    images: [
      {
        order: 0,
        url:
          'https://carsguide-res.cloudinary.com/image/upload/f_auto,fl_lossy,q_auto,t_cg_hero_large/v1/editorial/dp/images/uploads/bmw-i5-rendering-W.jpg',
      },
    ],
  },
  {
    _id: 3,
    model: 'A4',
    make: 'Audi',
    regDate: '2006',
    power: 110,
    capacity: 2000,
    mileage: 50000,
    bodyType: 'sedan',
    price: 10000,
    priceDiscount: 5,
    fuel: 'diesel',
    transmission: 'manual',
    city: 'Tallinn',
    countryCode: 'EE',
    country: 'Estonia',
    urgent: true,
    featured: true,
    recommended: false,
    images: [
      {
        order: 0,
        url:
          'https://img.longo.group/drz5zvoaf/image/upload/c_fill,f_jpg,h_813,w_1084/hpkyty62jlu5hm94cdu4.jpg',
      },
    ],
  },
  {
    _id: 6,
    model: 'A4',
    make: 'Audi',
    regDate: '2006',
    power: 110,
    capacity: 2000,
    mileage: 50000,
    bodyType: 'sedan',
    price: 10000,
    priceDiscount: 5,
    fuel: 'diesel',
    transmission: 'manual',
    city: 'Tallinn',
    countryCode: 'EE',
    country: 'Estonia',
    urgent: true,
    featured: true,
    recommended: false,
    images: [
      {
        order: 0,
        url:
          'https://img.longo.group/drz5zvoaf/image/upload/c_fill,f_jpg,h_813,w_1084/hpkyty62jlu5hm94cdu4.jpg',
      },
    ],
  },
  {
    _id: 7,
    model: 'A4',
    make: 'Audi',
    regDate: '2006',
    power: 110,
    capacity: 2000,
    mileage: 50000,
    bodyType: 'sedan',
    price: 10000,
    priceDiscount: 5,
    fuel: 'diesel',
    transmission: 'manual',
    city: 'Tallinn',
    countryCode: 'EE',
    country: 'Estonia',
    urgent: true,
    featured: true,
    recommended: false,
    images: [
      {
        order: 0,
        url:
          'https://img.longo.group/drz5zvoaf/image/upload/c_fill,f_jpg,h_813,w_1084/hpkyty62jlu5hm94cdu4.jpg',
      },
    ],
  },
  {
    _id: 8,
    model: 'A4',
    make: 'Audi',
    regDate: '2006',
    power: 110,
    capacity: 2000,
    mileage: 50000,
    bodyType: 'sedan',
    price: 10000,
    priceDiscount: 5,
    fuel: 'diesel',
    transmission: 'manual',
    city: 'Tallinn',
    countryCode: 'EE',
    country: 'Estonia',
    urgent: true,
    featured: true,
    recommended: false,
    images: [
      {
        order: 0,
        url:
          'https://img.longo.group/drz5zvoaf/image/upload/c_fill,f_jpg,h_813,w_1084/hpkyty62jlu5hm94cdu4.jpg',
      },
    ],
  },
  {
    _id: 9,
    model: 'A4',
    make: 'Audi',
    regDate: '2006',
    power: 110,
    capacity: 2000,
    mileage: 50000,
    bodyType: 'sedan',
    price: 10000,
    priceDiscount: 5,
    fuel: 'diesel',
    transmission: 'manual',
    city: 'Tallinn',
    countryCode: 'EE',
    country: 'Estonia',
    urgent: true,
    featured: true,
    recommended: false,
    images: [
      {
        order: 0,
        url:
          'https://img.longo.group/drz5zvoaf/image/upload/c_fill,f_jpg,h_813,w_1084/hpkyty62jlu5hm94cdu4.jpg',
      },
    ],
  },
]

export default vehicles
